import type { BotProfile, EmojiDefinition, EmojiId } from "./contracts.ts";

export const EMOJI_IDS: EmojiId[] = [
  "fire",
  "water",
  "lightning",
  "ice",
  "magnet",
  "bomb",
  "mirror",
  "hole",
  "shield",
  "snake",
  "soap",
  "plant",
  "wind",
  "heart",
  "ghost",
  "chain",
];

export const EMOJI_DEFINITIONS: Record<EmojiId, EmojiDefinition> = {
  fire: {
    id: "fire",
    displayName: "Fire",
    role: "element",
    primaryVerb: "burn",
    whySummary: "Fire burns fragile or scaling targets before they can stabilize.",
    counters: ["plant", "ice", "heart", "ghost"],
    failsAgainst: ["water", "soap", "shield"],
    stats: { hp: 6, attack: 3, speed: 5, preferredRow: "front", tags: ["frontline", "burn"] },
  },
  water: {
    id: "water",
    displayName: "Water",
    role: "element",
    primaryVerb: "extinguish",
    whySummary: "Water neutralizes unstable heat and energy lines.",
    counters: ["fire", "lightning", "hole", "bomb"],
    failsAgainst: ["ice", "plant", "wind"],
    stats: { hp: 7, attack: 2, speed: 5, preferredRow: "front", tags: ["frontline", "control"] },
  },
  lightning: {
    id: "lightning",
    displayName: "Lightning",
    role: "element",
    primaryVerb: "stun",
    whySummary: "Lightning wins on timing by stunning combo engines and divers.",
    counters: ["magnet", "ice", "ghost", "heart"],
    failsAgainst: ["water", "mirror", "hole"],
    stats: { hp: 5, attack: 3, speed: 8, preferredRow: "back", tags: ["tempo", "stun", "backline_reach"] },
  },
  ice: {
    id: "ice",
    displayName: "Ice",
    role: "element",
    primaryVerb: "freeze",
    whySummary: "Ice freezes explosive lines and stabilizes the frontline.",
    counters: ["water", "bomb", "snake", "wind"],
    failsAgainst: ["fire", "lightning", "heart"],
    stats: { hp: 8, attack: 2, speed: 4, preferredRow: "front", tags: ["frontline", "freeze", "anti_hazard"] },
  },
  magnet: {
    id: "magnet",
    displayName: "Magnet",
    role: "trick",
    primaryVerb: "pull",
    whySummary: "Magnet wins when it drags protected threats into losing lines.",
    counters: ["bomb", "shield", "heart"],
    failsAgainst: ["lightning", "mirror", "chain", "ghost"],
    stats: { hp: 6, attack: 2, speed: 6, preferredRow: "flex", tags: ["pull", "combo"] },
  },
  bomb: {
    id: "bomb",
    displayName: "Bomb",
    role: "hazard",
    primaryVerb: "explode",
    whySummary: "Bomb is a swing piece that punishes teams that fail to answer it.",
    counters: ["plant", "heart", "soap", "mirror"],
    failsAgainst: ["ice", "hole", "magnet", "shield"],
    stats: { hp: 5, attack: 4, speed: 3, preferredRow: "back", tags: ["splash", "hazard", "heavy"] },
  },
  mirror: {
    id: "mirror",
    displayName: "Mirror",
    role: "trick",
    primaryVerb: "reflect",
    whySummary: "Mirror punishes targeted aggression and obvious combo attempts.",
    counters: ["lightning", "magnet", "chain"],
    failsAgainst: ["bomb", "hole", "ghost"],
    stats: { hp: 5, attack: 2, speed: 5, preferredRow: "back", tags: ["reflect", "counter"] },
  },
  hole: {
    id: "hole",
    displayName: "Hole",
    role: "trick",
    primaryVerb: "delete",
    whySummary: "Hole deletes a narrow set of high-impact threats before they matter.",
    counters: ["bomb", "lightning", "wind"],
    failsAgainst: ["water", "plant", "ghost"],
    stats: { hp: 5, attack: 2, speed: 4, preferredRow: "back", tags: ["delete", "anti_hazard"] },
  },
  shield: {
    id: "shield",
    displayName: "Shield",
    role: "guard_support",
    primaryVerb: "block",
    whySummary: "Shield blocks one meaningful hit and gives slower teams time to stabilize.",
    counters: ["fire", "lightning", "snake", "ghost"],
    failsAgainst: ["magnet", "chain", "bomb"],
    stats: { hp: 9, attack: 1, speed: 3, preferredRow: "front", tags: ["frontline", "block", "tank"] },
  },
  snake: {
    id: "snake",
    displayName: "Snake",
    role: "status_ramp",
    primaryVerb: "poison",
    whySummary: "Snake wins long fights by stacking poison on teams without cleanse.",
    counters: ["water", "magnet", "heart", "plant"],
    failsAgainst: ["soap", "ice", "fire"],
    stats: { hp: 6, attack: 2, speed: 5, preferredRow: "back", tags: ["poison", "attrition"] },
  },
  soap: {
    id: "soap",
    displayName: "Soap",
    role: "guard_support",
    primaryVerb: "cleanse",
    whySummary: "Soap resets messy status fights and keeps support comps alive.",
    counters: ["snake", "fire", "chain"],
    failsAgainst: ["ghost", "bomb", "plant"],
    stats: { hp: 6, attack: 1, speed: 4, preferredRow: "back", tags: ["cleanse", "support"] },
  },
  plant: {
    id: "plant",
    displayName: "Plant",
    role: "status_ramp",
    primaryVerb: "grow",
    whySummary: "Plant rewards protection and positioning if it survives the opening.",
    counters: ["water", "shield", "mirror", "hole"],
    failsAgainst: ["fire", "snake", "bomb", "wind"],
    stats: { hp: 7, attack: 1, speed: 3, preferredRow: "back", tags: ["grow", "ramp"] },
  },
  wind: {
    id: "wind",
    displayName: "Wind",
    role: "trick",
    primaryVerb: "push",
    whySummary: "Wind scatters clumped teams and punishes rigid frontline setups.",
    counters: ["plant", "heart", "bomb", "water"],
    failsAgainst: ["chain", "shield", "ice"],
    stats: { hp: 5, attack: 2, speed: 8, preferredRow: "flex", tags: ["push", "tempo", "anti_clump"] },
  },
  heart: {
    id: "heart",
    displayName: "Heart",
    role: "guard_support",
    primaryVerb: "heal",
    whySummary: "Heart extends fights so carefully protected teams can realize their plan.",
    counters: ["ice", "shield", "plant"],
    failsAgainst: ["ghost", "snake", "bomb", "lightning"],
    stats: { hp: 7, attack: 1, speed: 5, preferredRow: "back", tags: ["heal", "support"] },
  },
  ghost: {
    id: "ghost",
    displayName: "Ghost",
    role: "trick",
    primaryVerb: "phase",
    whySummary: "Ghost slips past the frontline once and punishes fragile backline pieces.",
    counters: ["heart", "soap", "bomb", "plant", "mirror"],
    failsAgainst: ["chain", "lightning", "shield"],
    stats: { hp: 5, attack: 3, speed: 8, preferredRow: "back", tags: ["phase", "dive", "backline_reach"] },
  },
  chain: {
    id: "chain",
    displayName: "Chain",
    role: "trick",
    primaryVerb: "bind",
    whySummary: "Chain shuts down movement-based combos and stabilizes chaotic battles.",
    counters: ["magnet", "wind", "ghost", "bomb"],
    failsAgainst: ["soap", "heart", "fire"],
    stats: { hp: 8, attack: 2, speed: 5, preferredRow: "front", tags: ["bind", "control", "anti_combo"] },
  },
};

export const PRACTICE_BOT_DECK: EmojiId[] = ["shield", "water", "ice", "soap", "plant", "heart"];
export const SMART_BOT_DECK: EmojiId[] = ["lightning", "magnet", "bomb", "ghost", "chain", "wind"];

export const BOT_PROFILES: Record<"practice" | "smart", BotProfile> = {
  practice: {
    id: "practice",
    difficulty: "bot_practice",
    aggression: 0.35,
    defenseBias: 0.7,
    comboBias: 0.2,
  },
  smart: {
    id: "smart",
    difficulty: "bot_smart",
    aggression: 0.7,
    defenseBias: 0.45,
    comboBias: 0.8,
  },
};
