create extension if not exists pgcrypto;

create type public.match_mode as enum ('pvp_ranked', 'bot_practice', 'bot_smart');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Player',
  avatar_key text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.decks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Main Deck',
  emoji_ids text[] not null check (array_length(emoji_ids, 1) = 6),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  mode public.match_mode not null,
  status text not null default 'pending',
  player_a uuid not null references auth.users(id) on delete cascade,
  player_b uuid references auth.users(id) on delete cascade,
  bot_profile_id text,
  deck_a text[] not null default '{}',
  deck_b text[] not null default '{}',
  bans jsonb not null default '{}'::jsonb,
  current_state jsonb not null default '{}'::jsonb,
  winner uuid references auth.users(id),
  rules_version text not null default 'launch-001',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  round_number integer not null check (round_number > 0),
  result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (match_id, round_number)
);

create table if not exists public.turns (
  id uuid primary key default gen_random_uuid(),
  match_id uuid not null references public.matches(id) on delete cascade,
  round_number integer not null check (round_number > 0),
  player_id uuid not null references auth.users(id) on delete cascade,
  emoji_id text not null,
  locked_at timestamptz not null default timezone('utc', now()),
  unique (match_id, round_number, player_id)
);

create table if not exists public.ratings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_elo integer not null default 1200,
  wins integer not null default 0,
  losses integer not null default 0,
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.codex_unlocks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  interaction_key text not null,
  reason_code text not null,
  summary text not null,
  tip text not null,
  unlocked_at timestamptz not null default timezone('utc', now()),
  unique (user_id, interaction_key, reason_code)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_decks_updated_at on public.decks;
create trigger set_decks_updated_at before update on public.decks
for each row execute procedure public.set_updated_at();

drop trigger if exists set_matches_updated_at on public.matches;
create trigger set_matches_updated_at before update on public.matches
for each row execute procedure public.set_updated_at();

drop trigger if exists set_ratings_updated_at on public.ratings;
create trigger set_ratings_updated_at before update on public.ratings
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.decks enable row level security;
alter table public.matches enable row level security;
alter table public.rounds enable row level security;
alter table public.turns enable row level security;
alter table public.ratings enable row level security;
alter table public.codex_unlocks enable row level security;
alter table public.analytics_events enable row level security;

create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = user_id);

create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = user_id);

create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = user_id);

create policy "decks_select_own" on public.decks
for select using (auth.uid() = user_id);

create policy "decks_mutate_own" on public.decks
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "matches_select_participant" on public.matches
for select using (auth.uid() = player_a or auth.uid() = player_b);

create policy "matches_insert_player_a" on public.matches
for insert with check (auth.uid() = player_a);

create policy "matches_update_participant" on public.matches
for update using (auth.uid() = player_a or auth.uid() = player_b);

create policy "rounds_select_participant" on public.rounds
for select using (
  exists (
    select 1 from public.matches
    where public.matches.id = rounds.match_id
      and (public.matches.player_a = auth.uid() or public.matches.player_b = auth.uid())
  )
);

create policy "turns_select_participant" on public.turns
for select using (
  exists (
    select 1 from public.matches
    where public.matches.id = turns.match_id
      and (public.matches.player_a = auth.uid() or public.matches.player_b = auth.uid())
  )
);

create policy "turns_insert_participant" on public.turns
for insert with check (
  auth.uid() = player_id and
  exists (
    select 1 from public.matches
    where public.matches.id = turns.match_id
      and (public.matches.player_a = auth.uid() or public.matches.player_b = auth.uid())
  )
);

create policy "ratings_select_own" on public.ratings
for select using (auth.uid() = user_id);

create policy "ratings_insert_own" on public.ratings
for insert with check (auth.uid() = user_id);

create policy "ratings_update_own" on public.ratings
for update using (auth.uid() = user_id);

create policy "codex_select_own" on public.codex_unlocks
for select using (auth.uid() = user_id);

create policy "codex_insert_own" on public.codex_unlocks
for insert with check (auth.uid() = user_id);

create policy "analytics_insert_self_or_null" on public.analytics_events
for insert with check (user_id is null or auth.uid() = user_id);

create policy "analytics_select_own" on public.analytics_events
for select using (user_id is null or auth.uid() = user_id);
